name: CD Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server & deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.AWS_SSH_HOST }}  # Critical!
          username: ${{ secrets.AWS_SSH_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/hng12-stage2-fastapi-book-project
            git pull origin main
            pip install -r requirements.txt
            sudo systemctl restart fastapi.service
